<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SkyMasterATC.SimConnect</AssemblyName>
    <RootNamespace>SkyMasterATC.SimConnect</RootNamespace>
  </PropertyGroup>

</Project>
