<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SkyMasterATC.SimConnect</AssemblyName>
    <RootNamespace>SkyMasterATC.SimConnect</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyMasterATC.Core\SkyMasterATC.Core.csproj" />
  </ItemGroup>

</Project>
